name    'counsyl-ruby'
version '0.9.3'
source  'git://github.counsyl.com/dev/puppet-ruby.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Ruby language runtime'
description 'Installs the Ruby language runtime'
project_page 'https://github.counsyl.com/dev/puppet-ruby'

dependency 'counsyl/sys', '>= 0.9.6'
