name    'counsyl-ruby'
version '1.0.0'
source 'git://github.counsyl.com/justin/counsyl-ruby.git'
author 'counsyl'
license 'Apache License, Version 2.0'
summary 'Installs the Ruby language runtime'
description 'Installs the Ruby language runtime'
project_page 'https://github.counsyl.com/justin/counsyl-ruby'

dependency 'counsyl/sys', '>= 1.0.0'
